version: '3.8'

networks:
  dev_net:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine  # Используем стандартный образ Nginx
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'  # Используем вашу кастомную конфигурацию
    networks:
      - dev_net

  bot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    ports:
      - "3002:3002"
    networks:
      - dev_net
  
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "3001:80"
    networks:
      - dev_net
      
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - dev_net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_DIRS: /bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      - dev_net
