version: '3.8'

networks:
  stage_net:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - bot
      - app
    networks:
      - stage_net
  
  bot:
    image: vovan2101/yocto-bot:stage
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - stage_net
    environment:
      - STAGE_POSTGRES_USER=${STAGE_POSTGRES_USER}
      - STAGE_POSTGRES_PASSWORD=${STAGE_POSTGRES_PASSWORD}
      - STAGE_POSTGRES_DB=${STAGE_POSTGRES_DB}
      - STAGE_POSTGRES_HOST=${STAGE_POSTGRES_HOST}
      - STAGE_POSTGRES_PORT=${STAGE_POSTGRES_PORT}
  
  app:
    image: vovan2101/yocto-app:stage
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - STAGE_POSTGRES_USER=${STAGE_POSTGRES_USER}
      - STAGE_POSTGRES_PASSWORD=${STAGE_POSTGRES_PASSWORD}
      - STAGE_POSTGRES_DB=${STAGE_POSTGRES_DB}
      - STAGE_POSTGRES_HOST=${STAGE_POSTGRES_HOST}
      - STAGE_POSTGRES_PORT=${STAGE_POSTGRES_PORT}
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - FROM_GMAIL_EMAIL=${FROM_GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    networks:
      - stage_net

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - STAGE_POSTGRES_USER=${STAGE_POSTGRES_USER}
      - STAGE_POSTGRES_PASSWORD=${STAGE_POSTGRES_PASSWORD}
      - STAGE_POSTGRES_DB=${STAGE_POSTGRES_DB}
      - STAGE_POSTGRES_HOST=${STAGE_POSTGRES_HOST}
      - STAGE_POSTGRES_PORT=${STAGE_POSTGRES_PORT}
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - FROM_GMAIL_EMAIL=${FROM_GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - stage_net
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - stage_net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_DIRS: /bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      - stage_net

volumes:
  postgres_data: