version: '3.8'

networks:
  stage_net:  # или используйте stage_net на вашем stage инстансе

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - bot
      - app
    networks:
      - stage_net
  
  bot:
    image: vovan2101/yocto-bot:stage  # Для stage-инстанса, используйте :stage на stage-инстансе
    networks:
      - stage_net
  
  app:
    image: vovan2101/yocto-app:stage  # Для stage-инстанса, используйте :stage на stage-инстансе
    networks:
      - stage_net
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - stage_net
    volumes:
      - ./zookeeper_data:/bitnami/zookeeper/data  # Постоянное хранилище
      - ./zookeeper_logs:/bitnami/zookeeper/logs  # Постоянное хранилище

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_DIRS: /bitnami/kafka  # Указание директории для логов
    depends_on:
      - zookeeper
    networks:
      - stage_net
    volumes:
      - ./kafka_data:/bitnami/kafka  # Постоянное хранилище
