version: '3.8'

networks:
  dev_net:  # создаем сеть для локальной разработки
    driver: bridge

services:
  nginx:
    build:  # Сборка локальной версии Nginx
      context: .
      dockerfile: ./nginx.Dockerfile # Можете указать путь к Dockerfile для Nginx, если нужно
    ports:
      - "8080:80"   # Измените порт на 8080 для локальной разработки
    volumes:
      - './nginx.dev.conf:/etc/nginx/conf.d/default.conf'  # Используем локальную конфигурацию Nginx
    depends_on:
      - bot
      - app
    networks:
      - dev_net
  
  bot:
    build:  # Для локальной разработки используем сборку
      context: ./bot
      dockerfile: ./Dockerfile
    ports:
      - "3002:3002"
    networks:
      - dev_net
  
  app:
    build:  # Для локальной разработки используем сборку
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "3001:80"  # Добавим порт для локальной разработки
    networks:
      - dev_net
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - dev_net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LOG_DIRS: /bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      - dev_net
