version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - bot
      - app
    networks:
      - dev
  
  bot:
    build:
      context: ./bot
    networks:
      - dev
  
  app:
    build:
      context: ./app
    networks:
      - dev
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - dev
    volumes:
      - type: tmpfs
        target: /bitnami/zookeeper/data
      - type: tmpfs
        target: /bitnami/zookeeper/logs

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper
    networks:
      - dev
    volumes:
      - type: tmpfs
        target: /bitnami/kafka
