const fillhustleFundForm = require('./hustleFundForm');

const testFormData = {
  first_name: 'ksdas',
  last_name: 'asda',
  email: 'sadasd@gmail.com',
  phone_number: '',
  relationship: '',
  other_relationship: '',
  working_full_time: 'Yes',
  full_time_duration: '36 Months or More',
  company_name: 'asdsa',
  one_line_description: '',
  company_description: 'kkjj',
  company_solution: 'lkkkl',
  pitch_description: '',
  target_customer: 'asdsad',
  customer_acquisition: [ 'Paid Advertisement', 'SEO' ],
  other_customer_acquisition: '',
  date_founded: 'null',
  product_status: 'Currently building MVP',
  active_customers: 'Yes',
  how_many_users: '101-300',
  industry: 'Audiotech, Big Data, asdsad',
  liberty_ventures_industry: '',
  other_industry: '',
  product: [ 'Software - Other', 'Digital Goods / Content' ],
  other_product: '',
  business_model: [ 'C2B', 'B2C / D2C' ],
  other_business_model: '',
  company_website: 'https://asdas.com',
  pitch_deck: 'https://asdas.com',
  pitch_deck_file: 'null',
  pitch_deck_file_name: '',
  headquartered: 'Middle East',
  headquartered_precursor: '',
  customers_based: 'Asia - Southeast Asia',
  other_customers_based: '',
  specific_location: '',
  other_specific_location: '',
  legal_structure: '',
  other_legal_structure: '',
  raising_round: 'Pre-Seed extension',
  beyond_series_a_round: '',
  earning_amount: '$1000-$4,999',
  raising_amount: '',
  earning_revenue: 'Yes',
  source_of_revenue: 'Affiliate',
  other_source_of_revenue: '',
  pre_money_valuation: '',
  post_money_valuation: '4343',
  capital_to_raise: '12321',
  prev_experience: '',
  team_description: '',
  company_linkedin: '',
  ceo_linkedin: 'https://sada.com',
  founder2_linkedin: '',
  founder3_linkedin: '',
  cto_linkedin: '',
  founder_video_url: '',
  vision: '',
  pitching_live: 'yes',
  share_submission: 'Yes',
  investors_participating: 'mmmmm',
  want_us_to_know: 'hjhjjh',
  value_of_team: '',
  industryString: 'Audiotech; Big Data; asdsad',
  productString: 'Software - Other; Digital Goods / Content',
  customer_acquisitionString: 'Paid Advertisement; SEO',
  selectedForms: [ 'Hustle Fund' ],
  businessModelString: 'C2B; B2C / D2C'
};
  
  
        
    

fillhustleFundForm(testFormData)
    .then(() => console.log('Test completed successfully'))
    .catch(error => console.error('Test encountered an error:', error));
