name: Docker Build and Push  # Название workflow

on:
  push:
    branches:
      - main  # Для production
      - stage  # Для тестирования (stage)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка и загрузка образа для 'bot' в ветке 'stage'
      - name: Build and push bot (stage)
        if: github.ref == 'refs/heads/stage'
        run: |
          docker build -t vovan2101/yocto-bot:stage -f ./bot/Dockerfile ./bot  # Указываем путь к Dockerfile в ./bot
          docker push vovan2101/yocto-bot:stage

      # Сборка и загрузка образа для 'app' в ветке 'stage'
      - name: Build and push app (stage)
        if: github.ref == 'refs/heads/stage'
        run: |
          docker build -t vovan2101/yocto-app:stage -f ./app/Dockerfile ./app  # Указываем путь к Dockerfile в ./app
          docker push vovan2101/yocto-app:stage

      # Сборка и загрузка образа для 'bot' в ветке 'main'
      - name: Build and push bot (prod)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t vovan2101/yocto-bot:prod -f ./bot/Dockerfile ./bot
          docker push vovan2101/yocto-bot:prod

      # Сборка и загрузка образа для 'app' в ветке 'main'
      - name: Build and push app (prod)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t vovan2101/yocto-app:prod -f ./app/Dockerfile ./app
          docker push vovan2101/yocto-app:prod
