name: Docker Build and Push  # Название workflow

on:
  push:
    branches:
      - main  # Для production
      - stage  # Для тестирования (stage)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка Docker Buildx (инструмент для сборки Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Шаг 3: Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Переменная для имени пользователя Docker Hub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Переменная для пароля Docker Hub

      # Сборка и загрузка образа для 'bot' и 'app' в ветке 'stage'
      - name: Build and push images for stage
        if: github.ref == 'refs/heads/stage'
        run: |
          docker build -t vovan2101/yocto-bot:stage -f ./bot/Dockerfile ./bot  # Сборка образа bot
          docker push vovan2101/yocto-bot:stage  # Пуш образа bot в Docker Hub
          docker build -t vovan2101/yocto-app:stage -f ./app/Dockerfile ./app  # Сборка образа app
          docker push vovan2101/yocto-app:stage  # Пуш образа app в Docker Hub

      # Сборка и загрузка образа для 'bot' и 'app' в ветке 'main'
      - name: Build and push images for prod
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t vovan2101/yocto-bot:prod -f ./bot/Dockerfile ./bot  # Сборка образа bot
          docker push vovan2101/yocto-bot:prod  # Пуш образа bot в Docker Hub
          docker build -t vovan2101/yocto-app:prod -f ./app/Dockerfile ./app  # Сборка образа app
          docker push vovan2101/yocto-app:prod  # Пуш образа app в Docker Hub
